*Multiple Regression* [Supervised Learning] is the phenomena of predicting the response variable
with the multiple input variable. this is mathematically represented as Y=F(x1)+F(x2).
The graphical representation of the SLR is a straight line of equation Y = m1X + m2X + c.

Applications:
  - used to predict rain fall
  - used to find stock prices

In [2]:
import pandas as pd
import numpy as np

In [3]:
dataset=pd.read_csv("Admission_Predict_Ver1.1.csv")

In [4]:
dataset

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
495         496        332          108                  5  4.5   4.0  9.02   
496         497        337          117                  5  5.0   5.0  9.87   
497         498        330          120                  5  4.5   5.0  9.56   
498         499        312          103                  4  4.0   5.0  8.43   
499         500        327          113                  4  4.5   4.5  9.04   

     Research  Chance of Admit   
0           1              0.92  
1           1              0.76  
2           1              0.72  
3           1              0.80  
4           0              0.65  
..        ...               ...  
495         1              0.87  
496         1              0.96  
497         1              0.93  
498         0              0.73  
499         0              0.84  

[500 rows x 9 columns]

In [5]:
dataset.shape

(500, 9)

In [6]:
dataset.head() #displays about the first 5 rows

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

In [7]:
dataset.tail() #displays about the last 5 rows

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
495         496        332          108                  5  4.5   4.0  9.02   
496         497        337          117                  5  5.0   5.0  9.87   
497         498        330          120                  5  4.5   5.0  9.56   
498         499        312          103                  4  4.0   5.0  8.43   
499         500        327          113                  4  4.5   4.5  9.04   

     Research  Chance of Admit   
495         1              0.87  
496         1              0.96  
497         1              0.93  
498         0              0.73  
499         0              0.84

In [8]:
data_set = dataset.drop(['Serial No.'],axis=1) #coloums axis=1 ; roes axis=0

In [9]:
dataset

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
495         496        332          108                  5  4.5   4.0  9.02   
496         497        337          117                  5  5.0   5.0  9.87   
497         498        330          120                  5  4.5   5.0  9.56   
498         499        312          103                  4  4.0   5.0  8.43   
499         500        327          113                  4  4.5   4.5  9.04   

     Research  Chance of Admit   
0           1              0.92  
1           1              0.76  
2           1              0.72  
3           1              0.80  
4           0              0.65  
..        ...               ...  
495         1              0.87  
496         1              0.96  
497         1              0.93  
498         0              0.73  
499         0              0.84  

[500 rows x 9 columns]

In [10]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values


In [11]:
x

array([[  1.  , 337.  , 118.  , ...,   4.5 ,   9.65,   1.  ],
       [  2.  , 324.  , 107.  , ...,   4.5 ,   8.87,   1.  ],
       [  3.  , 316.  , 104.  , ...,   3.5 ,   8.  ,   1.  ],
       ...,
       [498.  , 330.  , 120.  , ...,   5.  ,   9.56,   1.  ],
       [499.  , 312.  , 103.  , ...,   5.  ,   8.43,   0.  ],
       [500.  , 327.  , 113.  , ...,   4.5 ,   9.04,   0.  ]])

In [12]:
y

array([0.92, 0.76, 0.72, 0.8 , 0.65, 0.9 , 0.75, 0.68, 0.5 , 0.45, 0.52,
       0.84, 0.78, 0.62, 0.61, 0.54, 0.66, 0.65, 0.63, 0.62, 0.64, 0.7 ,
       0.94, 0.95, 0.97, 0.94, 0.76, 0.44, 0.46, 0.54, 0.65, 0.74, 0.91,
       0.9 , 0.94, 0.88, 0.64, 0.58, 0.52, 0.48, 0.46, 0.49, 0.53, 0.87,
       0.91, 0.88, 0.86, 0.89, 0.82, 0.78, 0.76, 0.56, 0.78, 0.72, 0.7 ,
       0.64, 0.64, 0.46, 0.36, 0.42, 0.48, 0.47, 0.54, 0.56, 0.52, 0.55,
       0.61, 0.57, 0.68, 0.78, 0.94, 0.96, 0.93, 0.84, 0.74, 0.72, 0.74,
       0.64, 0.44, 0.46, 0.5 , 0.96, 0.92, 0.92, 0.94, 0.76, 0.72, 0.66,
       0.64, 0.74, 0.64, 0.38, 0.34, 0.44, 0.36, 0.42, 0.48, 0.86, 0.9 ,
       0.79, 0.71, 0.64, 0.62, 0.57, 0.74, 0.69, 0.87, 0.91, 0.93, 0.68,
       0.61, 0.69, 0.62, 0.72, 0.59, 0.66, 0.56, 0.45, 0.47, 0.71, 0.94,
       0.94, 0.57, 0.61, 0.57, 0.64, 0.85, 0.78, 0.84, 0.92, 0.96, 0.77,
       0.71, 0.79, 0.89, 0.82, 0.76, 0.71, 0.8 , 0.78, 0.84, 0.9 , 0.92,
       0.97, 0.8 , 0.81, 0.75, 0.83, 0.96, 0.79, 0.

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [15]:
x_train.shape

(400, 8)

In [16]:
y_train.shape

(400,)

In [17]:
x_test.shape

(100, 8)

In [18]:
y_test.shape

(100,)

In [19]:
from sklearn.linear_model import LinearRegression

In [20]:
lm = LinearRegression()

In [21]:
lm.fit(x_train,y_train)

LinearRegression()

In [22]:
lm.coef_

array([8.63420868e-05, 2.06338765e-03, 3.34252471e-03, 4.67697292e-03,
       3.55945529e-03, 1.83217904e-02, 1.13353948e-01, 2.30319290e-02])

In [23]:
lm.intercept_

-1.387443916486907

In [24]:
y_pred=lm.predict(x_test)

In [25]:
y_pred

array([0.64855223, 0.83631124, 0.78022191, 0.89888581, 0.61863599,
       0.62593763, 0.53470978, 0.71990985, 0.51560535, 0.73519895,
       0.61055564, 0.70712359, 0.63147094, 0.76035135, 0.87887677,
       0.51485539, 0.8413721 , 0.65272855, 0.7561483 , 0.51485927,
       0.51032751, 0.72949117, 0.52082157, 0.9117646 , 0.81763852,
       0.74307177, 0.68430741, 0.51327231, 0.56840962, 0.59142766,
       0.7355418 , 0.4738788 , 0.64141599, 0.83346771, 0.5753016 ,
       0.61238562, 0.84891241, 0.88655504, 0.60147024, 0.65451322,
       0.67497534, 0.8829718 , 0.88244992, 0.72151821, 0.75944796,
       0.78279173, 0.97116556, 0.85996403, 0.65911239, 0.64654876,
       0.64051823, 0.62546904, 0.61981749, 0.79288132, 0.68287048,
       0.83477907, 0.53302884, 0.85644175, 0.60186026, 0.64571362,
       0.48207629, 0.9108896 , 0.62924802, 0.95676576, 0.72404326,
       0.61406759, 0.71339572, 0.86527513, 0.51617515, 0.76212218,
       0.8871168 , 0.76962788, 0.70510681, 0.66168246, 0.78638

In [26]:
y_test

array([0.64, 0.85, 0.8 , 0.91, 0.68, 0.54, 0.54, 0.65, 0.52, 0.79, 0.65,
       0.74, 0.64, 0.79, 0.89, 0.43, 0.81, 0.73, 0.8 , 0.58, 0.57, 0.74,
       0.6 , 0.93, 0.88, 0.67, 0.7 , 0.57, 0.48, 0.64, 0.69, 0.47, 0.57,
       0.87, 0.39, 0.53, 0.84, 0.89, 0.63, 0.7 , 0.72, 0.86, 0.91, 0.75,
       0.74, 0.76, 0.96, 0.81, 0.6 , 0.62, 0.69, 0.68, 0.59, 0.8 , 0.71,
       0.78, 0.69, 0.89, 0.67, 0.58, 0.44, 0.89, 0.53, 0.92, 0.66, 0.73,
       0.52, 0.86, 0.54, 0.72, 0.92, 0.55, 0.75, 0.73, 0.85, 0.91, 0.75,
       0.71, 0.54, 0.68, 0.62, 0.88, 0.59, 0.74, 0.8 , 0.63, 0.77, 0.65,
       0.57, 0.7 , 0.76, 0.78, 0.71, 0.73, 0.73, 0.95, 0.64, 0.53, 0.48,
       0.64])

In [27]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [28]:
mean_squared_error(y_test,y_pred)

0.003923718305661357

In [29]:
mean_absolute_error(y_test,y_pred)

0.048012986753218447

In [30]:
r2_score(y_test,y_pred)

0.7753349858623022